export const ratingData = [
    { rating: "D-", points: -35 },
    { rating: "D", points: -30 },
    { rating: "D+", points: -25 },
    { rating: "C-", points: -20 },
    { rating: "C", points: -15 },
    { rating: "C+", points: -10 },
    { rating: "B-", points: -5 },
    { rating: "B", points: 0 },
    { rating: "B+", points: 5 },
    { rating: "A-", points: 10 },
    { rating: "A", points: 15 },
    { rating: "A+", points: 20 },
    { rating: "S-", points: 25 },
    { rating: "S", points: 30 },
    { rating: "S+", points: 35 },
];
